export const FETCH_CATERGORY_DATA = "FECTH_CATEGORY";
export const FETCH_PRODUCTS_DATA = "FECTH_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_PRODUCT_QUANTITY = "UPDATE_CART_PRODUCT_QUANTITY";
export const SET_USER = "SET_USER";
